apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-jwt-secret
  namespace: production
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: auth-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: cotai-jwt-secret
